//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRRcp.Portal {
    
    
    public partial class ImportPDF {
        
        /// <summary>
        /// cntImportPDF_Kwitek control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HRRcp.Portal.Controls.cntImportPDF cntImportPDF_Kwitek;
        
        /// <summary>
        /// cntImportPDF_PIT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HRRcp.Portal.Controls.cntImportPDF cntImportPDF_PIT;
        
        /// <summary>
        /// cntImportPDF_Ocena control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HRRcp.Portal.Controls.cntImportPDF cntImportPDF_Ocena;
        
        /// <summary>
        /// cntImportPDF_RMUA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HRRcp.Portal.Controls.cntImportPDF cntImportPDF_RMUA;
        
        /// <summary>
        /// btnEdytuj control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnEdytuj;
        
        /// <summary>
        /// cntModal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HRRcp.RCP.Controls.cntModal cntModal;
        
        /// <summary>
        /// cntSciezkiPlikiEdit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HRRcp.Portal.Controls.Adm.cntSciezkiPlikiEdit cntSciezkiPlikiEdit;
        
        /// <summary>
        /// cntSciezkiPlikiEdit1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HRRcp.Portal.Controls.Adm.cntSciezkiPlikiEdit cntSciezkiPlikiEdit1;
        
        /// <summary>
        /// cntSciezkiPlikiEdit2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HRRcp.Portal.Controls.Adm.cntSciezkiPlikiEdit cntSciezkiPlikiEdit2;
    }
}
